# Generated by Django 2.0.5 on 2018-12-07 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_auto_20181205_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 7, 17, 1, 46, 303097, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
