# Generated by Django 2.1.2 on 2018-12-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_internship_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
