# Generated by Django 2.0.5 on 2018-12-05 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_courselike_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(through='courses.CourseLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='courselike',
            name='like',
        ),
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together={('course', 'user')},
        ),
    ]
