# Generated by Django 2.0.5 on 2018-12-05 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20181205_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='likes',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
