# Generated by Django 2.0.5 on 2018-12-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20181205_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecomment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courselike',
            name='user',
        ),
    ]
