# Generated by Django 2.0.5 on 2018-12-05 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20181205_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(through='courses.CourseLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courselike',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coursecomment',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together={('course', 'user')},
        ),
    ]
