# Generated by Django 2.1.2 on 2018-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
